### ISSUE TITLE
Check users can enter name in capital and non-capital letter and strip messages

### ISSUE THREAD

**Issue by InbarShirizly** [InbarShirizly/zoom_attendance_check#40]
- [ ] check in the code [session.py](https://github.com/InbarShirizly/zoom_attendance_check/blob/master/server/server/parsing/session.py) and make sure the code ignores "mistakes" like capital/non-capital letters and blank spaces
- [ ] check the changes passing the tests:
   - [test_session.py](https://github.com/InbarShirizly/zoom_attendance_check/blob/master/server/tests/test_session.py)
   - [test_attendance.py](https://github.com/InbarShirizly/zoom_attendance_check/blob/master/server/tests/test_attendance.py)

**Comment by bojanderson** [comment]
If you're still looking for somebody to do this, I probably could.

Do you just want me to create a Python script that tests a few examples of capital and no-capital letters for the same few names and checks that they work properly?

**Comment by InbarShirizly** [comment]
Hey @bojanderson , Thanks for wanting to contribute to the project! The best way it to [fork](https://docs.github.com/en/free-pro-team@latest/github/getting-started-with-github/fork-a-repo) the repository and add the changes in out files!

**So I will elaborate about this feature**:

- We are trying to parse the an Engilish zoom chat file, where the users might write there name with lowercase or upper case and might have spaces as well in the beginning or in the end of the sentence.
- The excel file of the students is: [link](https://github.com/InbarShirizly/zoom_attendance_check/blob/master/server/tests/files_to_test/students_list_excel/example_excel_english.xlsx) and the zoom chat file is [link](https://github.com/InbarShirizly/zoom_attendance_check/blob/master/server/tests/files_to_test/chat_files/chat_file_valid_english_nba.txt)
- As you can see in the text file some of the students write with these "mistakes" and we want to make sure the program assign this as the name.
- To do so, you will need to change the code in the file [session.py](https://github.com/InbarShirizly/zoom_attendance_check/blob/master/server/server/parsing/session.py) to make sure the messages are stripped and ignore lower cases - **just for the checking** - but still saving the authentic chat message.
- I think the change should happen around these lines of code
https://github.com/InbarShirizly/zoom_attendance_check/blob/4c3f725a62eb044a45eca25e7aab2d3a274b1fc0/server/server/parsing/session.py#L25-L29
- After finishing, make sure you are running the test files - and passing them:
   - [test_session.py](https://github.com/InbarShirizly/zoom_attendance_check/blob/master/server/tests/test_session.py)
   - [test_attendance.py](https://github.com/InbarShirizly/zoom_attendance_check/blob/master/server/tests/test_attendance.py)

for any questions, you can comment here or message me via Linkedin.

**Comment by bojanderson** [comment]
@InbarShirizly wow, thanks so much for the documentation of what you want done. I wish people at work were this detailed! I will get cracking on it.
