### ISSUE TITLE
User register screen doesn't show indication of successful registration

### ISSUE THREAD

**Issue by staveyal** [InbarShirizly/zoom_attendance_check#41]
When registering a new user, after pressing the submit button there's no client indication of a successful registration.

How to reproduce:
- Run both client web server and API server
- Register a new account

**Comment by adilanchian** [comment]
Hey there! 

Started working on this and just need to test it :). Should be in PR by the end of this week.

Adding code that looks like this:

```ts
const _renderRegistrationAlert = (failed: boolean) => {
    return (
      <Alert variant='outlined' severity={failed ? 'error' : 'success'} className={classes.alert}>
        {failed ? 'Failed to register. Please try again.' : 'Registration successful!'}
      </Alert>
    )
  }
...
<form onSubmit={handleSubmit}>
        {_renderRegistrationAlert(authState.failed)}
</form>
```

Assuming that things are working on the context side, this should be good to go!

**Comment by staveyal** [comment]
This looks great, make sure to assign me to your PR
Thank you very much for your support!

**Comment by adilanchian** [comment]
Added the notes in the PR, but will add here as well - 

Pretty much decided to go through a different process for successful registration. Let me know if this is cool with you!
